In [3]:
import numpy as np
import psycopg2

import sklearn.decomposition as sd

conn = psycopg2.connect(host="localhost", database="DataLake", user="yuhang")

cur = conn.cursor()
cur.execute("select id, unique_id, ref_0001, ref_0001vs, ref_0010, ref_0100, ref_0100vs, thick, wii_clip_1,\
ceno_clip_, x, y, z, class, age from yuhang.aem_shapefile where unique_id<160500")
inputrecord = np.array(cur.fetchall())
xyz = inputrecord[:, 10:13].astype(float)  # nx3 matrix
pca = sd.PCA(n_components=1)
pca.fit(xyz[:, 0:2])
xy = pca.transform(xyz[:, 0:2])

In [4]:
xyz

array([[3.4793180e+05, 7.3396325e+06, 5.8158000e+02],
       [3.4793180e+05, 7.3396325e+06, 5.7738000e+02],
       [3.4793180e+05, 7.3396325e+06, 5.7276000e+02],
       ...,
       [3.4956300e+05, 7.3415031e+06, 2.4599000e+02],
       [3.4956300e+05, 7.3415031e+06, 1.9093000e+02],
       [3.4956300e+05, 7.3415031e+06, 1.3325000e+02]])

In [5]:
xy

array([[ 1276.85296023],
       [ 1276.85296023],
       [ 1276.85296023],
       ...,
       [-1203.27988035],
       [-1203.27988035],
       [-1203.27988035]])

In [6]:
xy = inputrecord[:, 10:12].astype(float)


In [7]:
xy

array([[ 347931.8, 7339632.5],
       [ 347931.8, 7339632.5],
       [ 347931.8, 7339632.5],
       ...,
       [ 349563. , 7341503.1],
       [ 349563. , 7341503.1],
       [ 349563. , 7341503.1]])

In [8]:
xy-xy[0,:]

array([[   0. ,    0. ],
       [   0. ,    0. ],
       [   0. ,    0. ],
       ...,
       [1631.2, 1870.6],
       [1631.2, 1870.6],
       [1631.2, 1870.6]])

In [15]:
np.linalg.norm(xy-xy[0,:], axis=1)

array([   0.        ,    0.        ,    0.        , ..., 2481.92622775,
       2481.92622775, 2481.92622775])

In [17]:
3**3

27

In [18]:
x=np.array([1,2,3,4])

In [19]:
x**2

array([ 1,  4,  9, 16])